Repository 4Subsea/waveresponse-python, pull requests merged in 2022-12, with the labels that each got.

#35 ENH: mirror an RAO about a symmetry plane
  .gitignore
  docs/api_ref/index.rst
  docs/user_guide/concepts_utils/rao.rst
  src/waveresponse/__init__.py
  src/waveresponse/_core.py
  tests/test_core.py
Labels: feature

#33 Roll out workflow for automatic release notes and deployment. Include pull request template and labels.
  .github/workflows/deploy_public.yml
  docs/_templates/autosummary/class.rst
  docs/conf.py
  pyproject.toml
Labels: chore

#40 doc: parse release notes as md
  .github/workflows/deploy_public.yml
  docs/conf.py
  docs/release_notes.md
  docs/release_notes.rst
  pyproject.toml
Labels: documentation
