Repository 4Subsea/waveresponse-python, pull requests merged in 2023-01, with the labels that each got.

#42 Fix hovertab text
  docs/api_ref/index.rst
  docs/conf.py
Labels: chore

#43 Extend the mirror function to accept a symmetry plane
  docs/user_guide/concepts_utils/rao.rst
  src/waveresponse/_core.py
  tests/test_core.py
  tests/testdata/rao_heave_symmetric.csv
  tests/testdata/rao_pitch_symmetric.csv
  tests/testdata/rao_roll_symmetric.csv
  tests/testdata/rao_surge_symmetric.csv
  tests/testdata/rao_sway_symmetric.csv
  tests/testdata/rao_yaw_symmetric.csv
Labels: feature

#45 Add functionality for computing extreme values to DirectionalSpectrum class
  docs/user_guide/concepts_utils/directional_spectrum.rst
  docs/user_guide/concepts_utils/wave_spectrum.rst
  src/waveresponse/_core.py
  tests/test_core.py
Labels: feature

#49 Add Torsethaugen wave spectrum
  docs/api_ref/index.rst
  docs/user_guide/concepts_utils/directional_spectrum.rst
  docs/user_guide/standardized_spectra.rst
  src/waveresponse/__init__.py
  src/waveresponse/_standardized1d.py
  tests/test_standardized1d.py
  tests/testdata/hs0350_tp0550_torsethaugen.json
Labels: feature

#50 Add example on how to visualize a grid with matplotlib
  docs/conf.py
  docs/user_guide/concepts_utils/grid.rst
Labels: documentation
