Repository 4Subsea/waveresponse-python, pull requests merged in 2025-03, with the labels that each got.

#68 Fix numerical precision issue when comparing frequencies and directions between Grid-like objects
  src/waveresponse/_core.py
Labels: bug

#70 Allow negative complex-valued DirectionalSpectrum
  src/waveresponse/_core.py
  tests/test_core.py
Labels: feature

#69 Improve phase interpolation when using "polar" interpolation method
  src/waveresponse/_core.py
  tests/test_core.py
Labels: enhancement

#71 Define a base grid object
  src/waveresponse/_core.py
  src/waveresponse/_utils.py
  tests/test_core.py
  tests/test_utils.py
Labels: refactor

#72 Fix duplicate code in `Grid` class
  src/waveresponse/_core.py
  tests/test_core.py
Labels: bug

#73 Add direction binned Grid-like class `BinGrid`
  src/waveresponse/__init__.py
  src/waveresponse/_core.py
  tests/test_core.py
Labels: feature

#74 Mixin class for spectrum methods
  src/waveresponse/_core.py
Labels: enhancement
