Repository 4Subsea/waveresponse-python, pull requests merged in 2025-04, with the labels that each got.

#75 Add method for returning binned spectrum values
  src/waveresponse/_core.py
  tests/test_core.py
Labels: feature

#77 Add WaveBinSpectrum class
  src/waveresponse/__init__.py
  src/waveresponse/_core.py
  tests/test_core.py
Labels: feature

#78 Revert (refactor out) introduction of BinGrid
  src/waveresponse/__init__.py
  src/waveresponse/_core.py
  tests/test_core.py
Labels: refactor

#80 Extend available output_types for multiply with binned grid types
  src/waveresponse/_core.py
  tests/test_core.py
Labels: feature

#82 Calculate response with binned wave spectrum
  docs/user_guide/calculate_response.rst
  src/waveresponse/_core.py
  tests/test_core.py
Labels: enhancement

#83 Update documentation for new functionality
  docs/api_ref/index.rst
  docs/user_guide/calculate_response.rst
  docs/user_guide/concepts_utils/directional_bin_spectrum.rst
  docs/user_guide/concepts_utils/index.rst
  docs/user_guide/concepts_utils/wave_bin_spectrum.rst
  docs/user_guide/standardized_spectra.rst
  src/waveresponse/_core.py
Labels: documentation
